### ISSUE TITLE
retroDrop

### ISSUE THREAD

**Issue by McPoon** [romjacket/retroInvader#2]
I just installed retroInvader and let it do what it needed to after clicking 'quick'. I went to double click on retroDrop and I get a "Windows Script Host" error.  
Script: C:\Program Files (x86)\retroinvader\RIDR.vbs
Line: 4
Char: 1
Error: Permission denied
Code: 800A0046
Source: Microsoft VBScript runtime Error

Edit: So I fixed this error. Now when I try to start a rom it says "There was a problem accessing the server.  Check status file for details" Where is the status file?

**Comment by romjacket** [comment]
I googled your problem and it appears to be related to user permissions
with regard to the installation location.
you have 2 options:

reinstall to a folder you have full control over (eg: your documents folder)
or
give full control to the retroinvader folder to your user by following
these steps
right-click on the retroinvader folder: C:\program files (x86)\retroinvader
select properties
in the window that appears, select the "security" tab
under "group or user names" select your user name and click "allow" box for
"full control" in the box below.
click apply and retrodrop should work.

Thanks for letting me know about your problem so I can make retroinvader a
better program!!!

**Comment by McPoon** [comment]
Thanks for the prompt response. I got the same conclusion as well. =). My new problem is after clicking on a rom, it says "There was a problem accessing the server. Check status file for details" Where is the status file, or what does this mean exactly? Thanks!

**Comment by romjacket** [comment]
the status file can be found in (retroarch location\downloads\system
name\rom.ext.status)
however this may or may not help you troubleshoot the problem
what system you're trying to download a rom for?
can you download a rom for any system?

**Comment by McPoon** [comment]
The downloads folder in retroArch seems to be empty. I tried to play a rom from Nes/SNES and Sega Genesis, after clicking on a rom it just pops up that error, then says download incomplete "ok" or "retry" retry brings the same error.

**Comment by romjacket** [comment]
I'm unable to reproduce this error.  Is it possible you don't have write
permission to the retroarch installation folder?

**Comment by McPoon** [comment]
You were correct, haha. I reinstalled at least 3 times and did the securities every time.. I guess somehow it wasn't saving with retroArch. Everything seems to be working great so far. Thanks a lot! Awesome app.
